security:
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 12
  providers:
    in_memory:
      memory:
        users:
          admin:
            password: $2y$12$sWdgmuCsAIrsPTPytunTDehBuu0KW9YOpZxXNDP8YaBMUCMjo5m.q
            roles: 'ROLE_ADMIN'
