security:
    providers:
        app_user_provider:
            memory:
                users:
                    admin:
                        password: $2y$13$C1cTzoJJFISgeXcfGukZK.PQP7VNnXgONVHj5/ZSAQnzKm35PTiqS
                        roles:
                            - ROLE_ADMIN
